export type FooterLanguage = "he" | "en"

export const FOOTER_SIGNATURE_TEXT = {
  he: {
    title: "חתימה דיגיטלית מאובטחת",
    body: "מסמך ממוחשב הופק על ידי ngisD של WOV",
  },
  en: {
    title: "Secure digital signature",
    body: "Computerized document generated by VOW",
  },
} as const

export function getFooterSignatureText(language: FooterLanguage) {
  return FOOTER_SIGNATURE_TEXT[language]
}
