export type FooterLanguage = "he" | "en"

export const FOOTER_SIGNATURE_TEXT = {
  he: {
    title: "חתימה דיגיטלית מאובטחת",
    // The Latin runs are stored reversed on purpose — "ngisD" is Dsign, "tnellexU"
    // is Uxellent — because pdf-lib draws glyphs in stored order with no BiDi pass.
    // Keep any Latin word added here reversed too, or it will print backwards.
    body: "מסמך ממוחשב הופק על ידי ngisD של tnellexU",
  },
  en: {
    title: "Secure digital signature",
    body: "Computerized document generated by Uxellent",
  },
} as const

export function getFooterSignatureText(language: FooterLanguage) {
  return FOOTER_SIGNATURE_TEXT[language]
}
