import "server-only"

import path from "node:path"
import { readFile } from "node:fs/promises"
import { PDFDocument, rgb } from "pdf-lib"
import fontkit from "@pdf-lib/fontkit"

const mmToPt = (mm: number) => (mm * 72) / 25.4

let cachedAssistantTtf: Buffer | null = null
let cachedAssistantTtfName: string | null = null

function looksLikeTtfOrOtf(buf: Buffer): boolean {
  if (!buf || buf.length < 4) return false
  // TrueType: 0x00010000 or "true" or "typ1"
  const b0 = buf[0]
  const b1 = buf[1]
  const b2 = buf[2]
  const b3 = buf[3]
  const tag = buf.toString("ascii", 0, 4)
  if (b0 === 0x00 && b1 === 0x01 && b2 === 0x00 && b3 === 0x00) return true
  if (tag === "OTTO") return true // OpenType CFF
  if (tag === "true" || tag === "typ1") return true
  return false
}

async function loadHebrewTtf(): Promise<{ name: string; buf: Buffer } | null> {
  if (cachedAssistantTtf && cachedAssistantTtfName) {
    return { name: cachedAssistantTtfName, buf: cachedAssistantTtf }
  }

  const candidates = ["AssistantRegular.ttf", "AlefRegular.ttf"]
  for (const filename of candidates) {
    try {
      const ttfPath = path.join(process.cwd(), "public", filename)
      const buf = await readFile(ttfPath)
      if (!looksLikeTtfOrOtf(buf)) continue
      cachedAssistantTtf = buf
      cachedAssistantTtfName = filename
      return { name: filename, buf }
    } catch {
      // try next candidate
    }
  }

  return null
}

export async function stampPdfFooter(params: {
  pdfBytes: Buffer
  language: "he" | "en"
  generatedAtText: string
  generatedByText: string
}): Promise<Buffer> {
  try {
    const doc = await PDFDocument.load(new Uint8Array(params.pdfBytes))
    const pages = doc.getPages()
    const total = pages.length

    let font = await doc.embedFont("Helvetica")
    let hasUnicodeFont = false
    const ttf = params.language === "he" ? await loadHebrewTtf() : null
    if (params.language === "he" && ttf) {
      try {
        doc.registerFontkit(fontkit as any)
        // DSIGN compatibility: avoid font subsetting (some signers/PDF parsers are sensitive).
        font = await doc.embedFont(new Uint8Array(ttf.buf), { subset: false })
        hasUnicodeFont = true
      } catch (e: any) {
        // fallback: keep Helvetica (avoid breaking issuance)
        hasUnicodeFont = false
      }
    }

    const fontSize = 9
    const badgeTitleSize = 12
    const badgeBodySize = 9

    const leftMargin = mmToPt(8)
    const rightMargin = mmToPt(8)
    const lineYFromBottom = mmToPt(12) + 15 // line a bit above text
    const textYFromBottom = mmToPt(7)

    const lineColor = rgb(0.90, 0.90, 0.90)
    const textColor = rgb(0.07, 0.07, 0.07)

    for (let i = 0; i < pages.length; i++) {
      const page = pages[i]
      const w = page.getWidth()

      const pageNumberText =
        params.language === "he" && hasUnicodeFont
          ? `עמוד ${i + 1} מתוך ${total}`
          : `Page ${i + 1} of ${total}`

      // Avoid non-ASCII text when we don't have a Unicode font embedded (prevents WinAnsi encode errors).
      const badgeTitle =
        params.language === "he" && hasUnicodeFont ? "חתימה דיגיטלית מאובטחת" : "Secure digital signature"
      const badgeBody =
        params.language === "he" && hasUnicodeFont
          ? ".VOW של Dsign ידי על הופק ממוחשב מסמך"
          : "Computerized document generated by Dsign of VOW."

      const leftText = `${params.generatedAtText || ""}`

      // separator line
      page.drawLine({
        start: { x: leftMargin, y: lineYFromBottom },
        end: { x: w - rightMargin, y: lineYFromBottom },
        thickness: 0.5,
        color: lineColor,
      })

      const centerWidth = font.widthOfTextAtSize(pageNumberText, fontSize)
      const centerX = (w - centerWidth) / 2
      page.drawText(pageNumberText, { x: centerX, y: textYFromBottom, size: fontSize, font, color: textColor })

      // left aligned
      page.drawText(leftText, { x: leftMargin, y: textYFromBottom, size: fontSize, font, color: textColor })

      // right side badge (2 lines), right-aligned for Hebrew (RTL).
      const badgeTitleWidth = font.widthOfTextAtSize(badgeTitle, badgeTitleSize)
      const badgeBodyWidth = font.widthOfTextAtSize(badgeBody, badgeBodySize)
      const badgeTitleX = w - rightMargin - badgeTitleWidth
      const badgeBodyX = w - rightMargin - badgeBodyWidth

      // Title (simulate medium weight by drawing twice with tiny offset)
      page.drawText(badgeTitle, { x: badgeTitleX, y: textYFromBottom + mmToPt(4), size: badgeTitleSize, font, color: textColor })
      page.drawText(badgeTitle, { x: badgeTitleX + 0.25, y: textYFromBottom + mmToPt(4), size: badgeTitleSize, font, color: textColor })

      // Body
      page.drawText(badgeBody, { x: badgeBodyX, y: textYFromBottom - mmToPt(0.5), size: badgeBodySize, font, color: textColor })
    }

    // Some PDF parsers/signing services are sensitive to object streams/xref formats.
    // Save in a more compatible form.
    const out = await doc.save({ useObjectStreams: false })
    return Buffer.from(out)
  } catch (e: any) {
    // Never block issuance because of footer stamping.
    return params.pdfBytes

  }
}