export type AuditorScanStatus = "queued" | "running" | "done" | "failed"

export type AuditorScanStep =
  | "normalize"
  | "robots"
  | "sitemap"
  | "ai_files"
  | "sample"
  | "fetch_pages"
  | "extract"
  | "keyword_engine"
  | "keyword_analysis"
  | "topic_discovery"
  | "rules"
  | "ai_readiness"
  | "competitor_discovery"
  | "competitor_crawl"
  | "competitor_keywords"
  | "content_gap_analysis"
  | "recommendations"
  | "persist"
  | "done"

export type AuditorRuleCategory = "technical" | "schema" | "ai_readiness" | "tracking"
export type AuditorRuleStatus = "pass" | "warn" | "fail"
export type AuditorRuleImpact = "low" | "medium" | "high"
export type AuditorRuleEffort = "low" | "medium" | "high"

